### ISSUE TITLE
dct:haspart est trop général

### ISSUE THREAD

**Issue by jmvanel** [GrottoCenter/Karstlink-ontology#10]
L'utiliser à la fois pour dire qu'on a un document attaché à la grotte,
et un secteur de ladite grotte,
ça me parait trop polysémique !

Exemple Grotte "Gouffre Jean Bernard": éviter dct:haspart
Remplacer par
`foaf:isPrimaryTopicOf`
ou `foaf:page`
ou `dcterms:isReferencedBy`
Ce dernier ne renvoie explicitement vers rien (pas de rdfs:range ), donc on préfèrera un des 2 foaf: .

Pour un secteur de grotte, il faudrait trouver une notion de contenance physique, géométrique.

NOTE: en mettant à jour ontologie, formulaires, et exemples, il convient de référence cette issue par #NUMERO .

**Comment by urien** [comment]
Close via #12
