### ISSUE TITLE
Exemples CSV: ligne d'entête

### ISSUE THREAD

**Issue by jmvanel** [GrottoCenter/Karstlink-ontology#11]
On se réfère ici à l'exemple : example/Gouffre_Jean_Bernard.csv

# Utilisation d'URI abrégés comme noms de colonne

Tels quels, ces entêtes ne sont pas lisibles par un outil générique.
Les noms devraient être des termes Turtle abrégés, le préfixe suivant ceux fournis par le site de référence http://prefix.cc
Il y a au moins un outil qui utilise ceci: SF en ligne de commande:
https://github.com/jmvanel/semantic_forms/blob/master/doc/en/administration.md#semantize-raw-stuff
Donc remplacer
`latitude`
par
`w3geo:latitude`
etc

NOTE:
Le préfixe geo: a été voté pour geosparql , cf https://prefix.cc/geo ; j'ai enregistré
`@prefix w3geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>.`
pour celui que nous utilisons. Mais bien sûr déclarer comme d'habitude ceci est toujours légal:
`@prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> .`

# Utilisation de chemin d'URI abrégés comme noms de colonne

En Web sémantique, ce n'est pas la classe qui définit la relation, mais la relation qui dit la classe.
Donc remplacer
`LicenceDocument_attributionName`
par
`dct:rights/cc:attributionName`

L'intention est que le processeur CSV => RDF va générer un noeud anonyme : 
```turtle
DATA_PREFIX:1 dct:rights _:1 .
_:1 cc:attributionName "Frédéric Urien" .
```

Donc aussi remplacer
`Access_creator`
par
`foaf:isPrimaryTopicOf/dct:creator`

ET ajouter une colonne avec la valeur donnant la classe:
```csv
foaf:isPrimaryTopicOf/rdf:type
karstlink:Access
```

Cependant, ça pose un problème, car il y a 2 relations foaf:isPrimaryTopicOf : une pour Access, et une pour Description.
Voir autre issue ...

( note : cette fonctionnalité avec / à la SPARQL path, n'est pas encore implémentée dans SF en ligne de commande )

# Ajouter une colonne pour le type

Ajouter une colonne pour le type, avec l'entête rdf:type; pour notre exemple, cela donne:
```csv
rdf:type
karstlink:UndergroundCavity
```

# Ajouter une colonne pour l'identifiant local

Il est bon d'avoir un identifiant local, autrement le processeur CSV => RDF va utiliser le numéro de ligne avec un préfixe choisi à l'exécution.
Pour cela on utilisera le nom de colonne `id` .
( note : cette fonctionnalité n'est pas encore implémentée dans SF en ligne de commande )

**Comment by urien** [comment]
Done
