### ISSUE TITLE
classes Access et Description à remplacer par foaf:Document ?

### ISSUE THREAD

**Issue by jmvanel** [GrottoCenter/Karstlink-ontology#12]
Et du coup, avoir une propriété `karstlink:hasAccessDocument` pointant vers un foaf:Document .
C'est en effet une propriété caractéristique du domaine conceptuel.
Utiliser une propriété permet d'aiguiller la sémantique dès le départ depuis l'objet Point ou UndergroundCavity .
C'est plus commode tant au niveau formulaire que pour le CSV.
Description en revanche n'a rien de spécifique du domaine conceptuel;
on peut utiliser foaf:isPrimaryTopicOf pointant vers un foaf:Document .

A NOTER:
DocumentSubject et DocumentType ne sont pas dans les exemples. DocumentSubject pourrait être utilisé via dct:subject pour caractériser les documents d'accès et de description.

**Comment by urien** [comment]
Closed by creation of karstlink hasDescriptionDocument and karstkink:hasAccessDocument
dct:subject an dct:type are already used.
