### ISSUE TITLE
Lien entre Observation et grotte

### ISSUE THREAD

**Issue by jmvanel** [GrottoCenter/Karstlink-ontology#8]
C'est quelque chose qui manque dans les exemples et l'ontologie.

Dans l'urgence, j'ai conseillé à Alain G. de relier ainsi une Observation et une grotte:
```turtle
@prefix karstlink: <https://ontology.uis-speleo.org/ontology/#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dwc:   <http://rs.tdwg.org/dwc/terms/> .
@prefix dwciri: <http://rs.tdwg.org/dwc/iri/> .

<https://geb.ffspeleo.fr/api/api/v2/1>
        rdf:type    karstlink:UndergroundCavity ;
        rdfs:label  "A24 (grotte aux Ours)" ;
        <https://www.w3.org/2003/01/geo/wgs84_pos#alt>  "1830" ;
        <https://www.w3.org/2003/01/geo/wgs84_pos#lat>  "46.1041" ;
        <https://www.w3.org/2003/01/geo/wgs84_pos#long>  "6.78107" .

<https://geb.ffspeleo.fr/api/api/v2/obs/1>
        rdf:type                 dwc:HumanObservation ;
        dwciri:inDescribedPlace  <https://geb.ffspeleo.fr/api/api/v2/1> ;
        dwc:associatedTaxa       "Ischyropsalis (GN), Stenophylax testacea (ES)" .
```
### la propriété dwciri:inDescribedPlace
Je me suis penché sur la propriété [dwciri:inDescribedPlace](http://rs.tdwg.org/dwc/iri/inDescribedPlace) . Ca dit:
_Use to link a dcterms:Location instance subject to the lowest level standardized hierarchically-described resource._
Et ailleurs ([RDF guide](https://dwc.tdwg.org/rdf/#275-names-of-geographic-subdivisions-normative)) il est écrit:
_dwciri:inDescribedPlace is used as an object property to link the dcterms:Location instance to an IRI for the lowest known geographic subdivision which applies to the locality. dwc:locality could also be used to provide a string literal description of the specific description of the place._
ce qui est plus clair.
Autrement dit, la dcterms:Location , un point anonyme avec des coordonnées, est reliée via dwciri:inDescribedPlace à l'URI d'un lieu (commune, lieu-dit) dans une référentiel géographique tel que geonames, dbpedia.org, Wikidata, [data.ign.fr](http://data.ign.fr/) .
Ce n'est pas exactement ce que nous avons ici. Cependant la grotte est bien une dcterms:Location, dans la [dernière version de l'ontologie](https://github.com/GrottoCenter/Karstlink-ontology/blob/master/ontology/karstlink.owl.ttl#L41) .
En fait l'intention est claire dans la version originelle de la donnée d'Alain, de lier directement l'observation à une grotte, et non pas à n'importe quel lieu.
```json
  "Underground cavity": [
    {
      "name": "A24 (grotte aux Ours)",
      "latitude": "46.1041",
      "longitude": "6.78107",
      "altitude": "1830",
      "observation": [
        {
          "occurence": [
            {
              "associated taxa": "Ischyropsalis (GN)"
            },
            {
              "associated taxa": "Stenophylax testacea (ES)"
```
Si on veut saisir une nouvelle observation sur une grotte déjà répertoriée, il convient d'avoir une propriété allant de observation vers grotte. Ainsi la complétion sur le type grotte fonctionnera.
**Je propose donc ceci dans l'ontologie:**
```turtle
karstlink:inUndergroundCavity a owl:ObjectProperty ;
   rdfs:isDefinedBy karstlink: ;
   rdfs:domain dwc:HumanObservation , dwc:Occurence ;
   rdfs:range karstlink:UndergroundCavity ;
   rdfs:label """dans la cavité"""@fr ;
   rdfs:label """in  Underground Cavity"""@en ; 
```
et bien sûr d'ajouter la propriété dans le formulaire observation.

Cependant, la propriété dwciri:inDescribedPlace mérite d'être utilisée, mais sur une grotte.
A NOTER; il y a aussi [dcterms:spatial](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/spatial) qui associe une dcterms:Location à n'importe quel URI; je n'en trouve pas d'usage pour l'instant.

**Comment by urien** [comment]
Dans le travail d'Alain occurence semble être une relation. dans le modèle c'est une classe https://dwc.tdwg.org/list/#dwc_Occurrence
Dans le modèle j'ai créé le lien entre l'observation (Occurrence) et la cavité avec dct:relation.
Qui est un lien sans doute trop générique mais qui doit fonctionner dans les 2 sens et qui fonctionnera avec toutes les observations. On va avoir des observations de nature très différentes qui seront décrites dans des ontologies différentes sur lesquelles nous n'avons pas commencé à travailler (géologie, hydrologie, paléo, ...)

**Comment by urien** [comment]
Mon choix s'est porté sur Occurence, plutot que HumanObservation, mais c'est peut être une mauvaise utilisation du modèle

**Comment by jmvanel** [comment]
Il est vrai qu'il y a [dcterms:relation](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/relation) dans [un exemple](https://ontology.uis-speleo.org/example/#A12y2016), et pour presque toutes les classes dans le formulaire .
Mais cette propriété est vraiment très vague, générale il est vrai, et potentiellement utile. Elle est encore plus générale que rdfs:seeAlso ; ce dernier ne permet que des URI, dcterms:relation permet des litéraux (chaînes) ou des URI.

Mais les cas d'usage cités par @urien pour des observations de natures différentes peuvent être couverts . SI on laisse
`    rdfs:domain dwc:HumanObservation , dwc:Occurence ;
`
on accepte que par inférence via `rdfs:domain` une observation de nature différente, disons géologie, devienne en même temps `dwc:HumanObservation` et `dwc:Occurence` .
Dans ce cas, `dwc:HumanObservation` ça va ,  mais `dwc:Occurence` est faux .
Je propose donc d'amender ma proposition ainsi : 
```turtle
karstlink:inUndergroundCavity a owl:ObjectProperty ;
   rdfs:isDefinedBy karstlink: ;
   rdfs:domain dwc:HumanObservation ;
   rdfs:range karstlink:UndergroundCavity ;
   rdfs:label """dans la cavité"""@fr ;
   rdfs:label """in  Underground Cavity"""@en .
```
**Commentaires sur le modèle RDF TDWG**
Ca mérite tout un article, que je compte faire en anglais, avec des exemples significatifs des principaux cas d'utilisation.
Disons seulement que l'usage effectif du modèle TDWG, ce sont les données tabulaires des Darwin Core Archives, qui sont le format de données importé et exporté par gbif.org .
Mais la documentation disponible RDF guide, https://dwc.tdwg.org/terms , ne donne pas vraiment des exemples significatifs, notamment sur les liens entre Location, HumanObservation, Event, GeologicalContext, Taxon, MeasurementOrFact, LivingSpecimen, PreservedSpecimen, FossilSpecimen.
Il n'y a aucun rdfs:domain ou rdfs:range .
Pris à la lettre, ce modèle conduit à une complexité inutile par la création de noeuds intermédiaires de types Occurrence, Organism, Identification , comme sur le site d'images de Steve Baskauf http://bioimages.vanderbilt.edu/ ; alors que très souvent ces 3 aspects sont un seul enregistrement dans les données concrètes JSON ou CSV .

**Comment by jmvanel** [comment]
Ma meilleure proposition; permet de rattacher explicitement une grotte à tout ce qu'on veut (plus de `rdfs:domain`):
```turtle
karstlink:relatedToUndergroundCavity a owl:ObjectProperty ;
   rdfs:isDefinedBy karstlink: ;
   rdfs:range karstlink:UndergroundCavity ;
   rdfs:label """à propos de la cavité"""@fr ;
   rdfs:label """related to Underground Cavity"""@en .
```
Le point important est qu'une ontologie centrée sur les grottes ne peut pas faire l'économie d'une propriété qui pointe vers une grotte. Le `rdfs:range` est important pour une IHM afin, via complétion, de proposer des grottes à rattacher.

**Comment by jmvanel** [comment]
Propriété karstlink:relatedToUndergroundCavity adoptée !
